=== Karmel0x/LeagueEmulatorJS/apps/gameserver/src/game/game.config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "map": {
            "type": "number"
        },
        "players": {
            "items": {
                "properties": {
                    "masteries": {
                        "maxItems": 0,
                        "minItems": 0,
                        "type": "array"
                    },
                    "match": {
                        "properties": {
                            "champion": {
                                "type": "string"
                            },
                            "num": {
                                "type": "number"
                            },
                            "skin": {
                                "type": "number"
                            },
                            "team": {
                                "type": "number"
                            }
                        },
                        "type": "object"
                    },
                    "runes": {
                        "maxItems": 0,
                        "minItems": 0,
                        "type": "array"
                    },
                    "summoner": {
                        "properties": {
                            "iconId": {
                                "type": "number"
                            },
                            "id": {
                                "type": "number"
                            },
                            "level": {
                                "type": "number"
                            },
                            "name": {
                                "type": "string"
                            },
                            "rankId": {
                                "type": "number"
                            },
                            "ribbonId": {
                                "type": "number"
                            },
                            "spells": {
                                "properties": {
                                    "d": {
                                        "type": "string"
                                    },
                                    "f": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        },
                        "type": "object"
                    }
                },
                "type": "object"
            },
            "type": "array"
        },
        "server": {},
        "version": {
            "type": "number"
        }
    },
    "type": "object"
}

=== Karmel0x/LeagueEmulatorJS/apps/gameserver/src/game/game.config.json
{
	"$schema": "./game.config.schema.json",
	"server": {
		"port": 5119,
		"host": "127.0.0.1"
	},
	"version": 4.20,
	"map": 1,
	"players": [
		{
			"summoner": {
				"id": 1,
				"name": "Player1",
				"level": 30,
				"iconId": 666,
				"rankId": 0,
				"ribbonId": 0,
				"spells": {
					"d": "SummonerHeal",
					"f": "SummonerFlash"
				}
			},
			"match": {
				"team": 100,
				"champion": "Ezreal",
				"skin": 0
			},
			"runes": [],
			"masteries": []
		},
		{
			"summoner": {
				"id": 2,
				"name": "Player2",
				"level": 30,
				"iconId": 666,
				"rankId": 0,
				"ribbonId": 0,
				"spells": {
					"d": "SummonerSmite",
					"f": "SummonerBoost"
				}
			},
			"match": {
				"team": 200,
				"champion": "Ezreal",
				"skin": 0
			},
			"runes": [],
			"masteries": []
		}
	]
}
